project_id = "pescarte-plataforma"

[api]
enabled = true
schemas = ["censo"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
port = 54321

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100
[db.migrations]
schema_paths = []

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://pescarte.org.br"
additional_redirect_urls = ["https://*.pescarte.org.br", "https://pescarte.org.br/signin/otp", "https://b7ec-179-187-120-40.ngrok-free.app"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 12
password_requirements = "lower_upper_letters_digits_symbols"
jwt_secret = ""
anon_key = ""
service_role_key = ""
[auth.rate_limit]
anonymous_users = 30
token_refresh = 200
sign_in_sign_ups = 30
token_verifications = 30
email_sent = 2

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.sessions]
timebox = "6m0s"
inactivity_timeout = "0s"
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = true
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600
[auth.email.template]
[auth.email.template.confirmation]
subject = "Finalize seu cadastro na Plataforma PEA Pescarte"
content_path = "supabase/templates/confirm_signup.html"
[auth.email.template.invite]
subject = "Convite para cadastro na Plataforma PEA Pescarte"
content_path = "supabase/templates/invite_user.html"
[auth.email.template.recovery]
subject = "Recuperação de senha da Plataforma PEA Pescarte"
content_path = "supabase/templates/reset_password.html"
[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"
[auth.sms.twilio]
enabled = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"

# Experimental features may be deprecated any time
[experimental]
# Configures Postgres storage engine to use OrioleDB (S3)
orioledb_version = ""
# Configures S3 bucket URL, eg. <bucket_name>.s3-<region>.amazonaws.com
s3_host = "env(S3_HOST)"
# Configures S3 bucket region, eg. us-east-1
s3_region = "env(S3_REGION)"
# Configures AWS_ACCESS_KEY_ID for S3 bucket
s3_access_key = "env(S3_ACCESS_KEY)"
# Configures AWS_SECRET_ACCESS_KEY for S3 bucket
s3_secret_key = "env(S3_SECRET_KEY)"